### ISSUE TITLE
maven里面的这个包是什么呢

### ISSUE THREAD

**Issue by TonyYule** [wukonggg/mz-g#4]
<dependency>
            <groupId>band.wukong</groupId>
            <artifactId>wukong-util</artifactId>
            <version>0.1.4a</version>
        </dependency>
        <dependency>
            <groupId>band.wukong.practice</groupId>
            <artifactId>wkp-barcode</artifactId>
            <version>0.1.0a</version>
        </dependency>

**Comment by wukonggg** [comment]
wukong-util在github上有，barcode自己反编译吧
[wkp-barcode-0.1.0a.zip](https://github.com/wukonggg/mz-g/files/432588/wkp-barcode-0.1.0a.zip)

**Comment by TomYule** [comment]
你可以把缺少的 jar 放到WEB-INF发布上来吗
